### PR TITLE
Fixed notebook for py3k.

### PR DESCRIPTION
**Pull request by pelson**
Thanks @stefanv! (bracket was in the wrong order after I added base64 encoding)

### CODE REVIEW

**Comment by stefanv** [comment]
Nice, thanks Phil!

**Comment by pelson** [comment]
Will deploy in a few mins.

**Comment by pelson** [comment]
Just confirmed that the notebook downloaded from https://repohealth.info/report/scikit-image/scikit-image does indeed work on py3k. 🎉

**Comment by pelson** [comment]
Incidentally, I have taken the decision within this repo to be ```py>=3.5```, and it is really only fortune that allows the notebook to work in py2 (and certainly not design)

**Comment by stefanv** [comment]
fortis Fortuna iuvat

**Pull request merged**
